---

- name: Install riemann-tools
  gem: name=riemann-tools state=latest user_install=no

- name: Install riemann client
  gem: name=riemann-client state=latest user_install=no

- name: Create service file
  template: src=riemann-health.service.j2 dest=/etc/systemd/system/riemann-health.service owner=root group=root mode=0644
  when: ansible_os_family == "Debian"
  notify:
    - reload systemd
    - restart riemann-health

- name: Start Riemann health
  service: name=riemann-health state=started
